2025-03-26 12:01:33,727 ERROR: Exception on /admin/dashboard [GET] [in C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\16673\Desktop\论坛1\app.py", line 202, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\Users\16673\Desktop\论坛1\app.py", line 223, in admin_dashboard
    return render_template('admin/dashboard.html', users=users)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\Users\16673\Desktop\论坛1\templates\admin\dashboard.html", line 1853, in template
    <td>{{ user.date_joined }}</td>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.
2025-03-26 12:01:33,766 ERROR: Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in c:\Users\16673\Desktop\论坛1\app.py:40]
2025-03-26 12:03:57,040 INFO: 论坛启动 [in c:\Users\16673\Desktop\论坛1\app.py:29]
2025-03-26 12:06:46,829 INFO: 论坛启动 [in c:\Users\16673\Desktop\论坛1\app.py:29]
2025-03-26 12:13:03,805 INFO: 论坛启动 [in c:\Users\16673\Desktop\论坛1\app.py:29]
2025-03-26 12:14:28,014 INFO: 论坛启动 [in c:\Users\16673\Desktop\论坛1\app.py:29]
2025-03-26 12:17:06,087 INFO: 论坛启动 [in c:\Users\16673\Desktop\论坛1\app.py:29]
2025-03-26 12:17:10,155 ERROR: Exception on /admin/dashboard [GET] [in C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\16673\Desktop\论坛1\app.py", line 202, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\Users\16673\Desktop\论坛1\app.py", line 223, in admin_dashboard
    return render_template('admin/dashboard.html', users=users)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\16673\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\Users\16673\Desktop\论坛1\templates\admin\dashboard.html", line 48, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'.
2025-03-26 12:17:10,163 ERROR: Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in c:\Users\16673\Desktop\论坛1\app.py:40]
2025-03-26 12:19:06,430 INFO: 论坛启动 [in c:\Users\16673\Desktop\论坛1\app.py:29]
2025-03-26 12:20:19,875 INFO: 论坛启动 [in c:\Users\16673\Desktop\论坛1\app.py:29]
2025-03-26 12:22:38,934 INFO: 论坛启动 [in c:\Users\16673\Desktop\论坛1\app.py:29]
2025-03-26 12:23:35,122 INFO: 论坛启动 [in c:\Users\16673\Desktop\论坛1\app.py:29]
2025-03-26 12:24:43,227 INFO: 论坛启动 [in c:\Users\16673\Desktop\论坛1\app.py:29]
2025-03-26 12:29:20,933 INFO: 论坛启动 [in c:\Users\16673\Desktop\论坛1\app.py:29]
2025-03-26 12:31:00,439 INFO: 论坛启动 [in c:\Users\16673\Desktop\论坛1\app.py:29]
2025-03-26 12:32:23,200 INFO: 论坛启动 [in c:\Users\16673\Desktop\论坛1\app.py:29]
2025-03-26 12:33:06,486 INFO: 论坛启动 [in c:\Users\16673\Desktop\论坛1\app.py:29]
2025-03-26 12:34:46,224 INFO: 论坛启动 [in c:\Users\16673\Desktop\论坛1\app.py:29]
2025-03-26 12:36:04,905 INFO: 论坛启动 [in c:\Users\16673\Desktop\论坛1\app.py:29]
2025-03-26 17:15:37,387 INFO: 论坛启动 [in c:\Users\16673\Desktop\论坛1\app.py:29]
2025-03-26 17:18:56,644 INFO: 论坛启动 [in c:\Users\16673\Desktop\论坛1\app.py:29]
2025-03-26 17:20:30,457 INFO: 论坛启动 [in c:\Users\16673\Desktop\论坛1\app.py:29]
2025-03-26 17:23:35,616 ERROR: Page not found: /favicon.ico [in c:\Users\16673\Desktop\论坛1\app.py:34]
2025-03-26 17:24:38,874 ERROR: Page not found: /favicon.ico [in c:\Users\16673\Desktop\论坛1\app.py:34]
2025-03-26 17:26:49,376 ERROR: Page not found: /favicon.ico [in c:\Users\16673\Desktop\论坛1\app.py:34]
2025-03-26 17:48:12,127 INFO: 论坛启动 [in c:\Users\16673\Desktop\论坛1\app.py:29]
